// react/calculadora/src/main/Calculator.jsx
import React, { Component } from 'react'
import './Calculator.css' // referenciando o css para o build
import Button from '../components/Button'
import Display from '../components/Display'

// objeto que representa estado inical da calculadora. Clear memory vai usar esse objeto para setar estado inicial
const initialState = {
    displayValue: '0',
    clearDisplay: false,
    operation: null,
    values: [0, 0], // array de mémoria para guardar dados de entrada
    current: 0 // variável que representa índice do array acima; para controle.
}

export default class Calculator extends Component {
    
    state = {...initialState} // clone do objeto initialState e atribui 

    constructor(props) {
        super(props)
         // variável que recebe função de dentro do objeto atual passando n como parâmetro. Garantindo o valor atual do this 
        this.clearMemory = this.clearMemory.bind(this)
        this.setOperation = this.setOperation.bind(this)
        this.addDigit = this.addDigit.bind(this)
    }

    // restaura para estado inicial ou objeto initialState
    clearMemory() {
        this.setState({ ...initialState })
    } 

    setOperation(operation) {
        if(this.state.current === 0) {
            this.setState({ operation, current:1, clearDisplay: true })
        }
        else {
            const equals = operation === '=' 
            

            const currentOperation = this.state.operation // pegando operação anterior

            const values = [...this.state.values]
            
            switch(currentOperation) {
                case '+':
                    values[0] = values[0] + values[1]
                    break
                case '-':
                    values[0] = values[0] - values[1]
                    break
                case '*':
                    values[0] = values[0] * values[1]
                    break
                case '/':
                    values[0] = values[0] / values[1]
                    break
                default:
                    values[0] = this.state.values[0]
                    console.log('Erro na operação!')      
            }

            values[1] =  0

            this.setState({
                displayValue: values[0],
                operation: equals ? null : operation,
                current: equals ? 0 : 1,
                clearDisplay: !equals,
                values
            })
        }
    }
    
    addDigit(n) {

        if( n === '.' && this.state.displayValue.includes('.')) { // regra para evitar duplicação do dígito '.' 
            return
        }
        
        const clearDisplay = this.state.displayValue === '0' || this.state.clearDisplay // duas situações para limpar display.

        const currentValue = clearDisplay ? '' : this.state.displayValue // defini valor corrente baseado na variável booleana clearDisplay
        
        const displayValue = currentValue + n // atribuição aditiva para cada valor de entrada salvando na variável displayValue
        
        this.setState({ displayValue, clearDisplay:false })

        if ( n !== '.') {
            const i = this.state.current // referencia índice para alteração do array values
            const newValue = parseFloat(displayValue) // converte toda a string para um float
            const values = [...this.state.values] // clona o array values do objeto state e atribui a values
            values[i] = newValue // altera valor baseado no índice
            this.setState({ values }) // modifica o array do objeto state já alterado
            console.log(values)
        }

    }

    render() {
       
        return (
            // class é uma palavra reservada do html, dentro do jsx é className    
            <div className="calculator"> 
                <Display value={this.state.displayValue} />
                <Button label="AC" click={this.clearMemory} triple />
                <Button label="/" click={this.setOperation} operation />
                <Button label="7" click={this.addDigit}/>
                <Button label="8" click={this.addDigit}/>
                <Button label="9" click={this.addDigit}/>
                <Button label="*" click={this.setOperation} operation/>
                <Button label="4" click={this.addDigit}/>
                <Button label="5" click={this.addDigit}/>
                <Button label="6" click={this.addDigit}/>
                <Button label="-" click={this.setOperation} operation/>
                <Button label="1" click={this.addDigit}/>
                <Button label="2" click={this.addDigit}/>
                <Button label="3" click={this.addDigit}/>
                <Button label="+" click={this.setOperation} operation/>
                <Button label="0" click={this.addDigit} double />
                <Button label="." click={this.addDigit}/>
                <Button label="=" click={this.setOperation} operation/>
            </div>
        )
    }
}

// vue/calculator/src/main/Calculator.vue
<template>
  <div class="calculator">
    <Display :value="displayValue" />
    <Button label="AC" triple @onClick="clearMemory" />
    <Button label="/" operation @onClick="setOperation" />
    <Button label="7" @onClick="addDigit" />
    <Button label="8" @onClick="addDigit" />
    <Button label="9" @onClick="addDigit" />
    <Button label="*" operation @onClick="setOperation" />
    <Button label="4" @onClick="addDigit" />
    <Button label="5" @onClick="addDigit" />
    <Button label="6" @onClick="addDigit" />
    <Button label="-" operation @onClick="setOperation" />
    <Button label="1" @onClick="addDigit" />
    <Button label="2" @onClick="addDigit" />
    <Button label="3" @onClick="addDigit" />
    <Button label="+" operation @onClick="setOperation" />
    <Button label="0" double @onClick="addDigit" />
    <Button label="." @onClick="addDigit" />
    <Button label="=" operation @onClick="setOperation" />
  </div>
</template>

<script>
import Button from "../components/Button";
import Display from "../components/Display";

export default {
  // vai retornar o estado inicial da calculadora
  data: function() {
    return {
      displayValue: "0",
      clearDisplay: false,
      operation: null,
      values: [0, 0],
      current: 0
    };
  },
  // registrando componentes
  components: { Button, Display },
  methods: {
    clearMemory() {
      Object.assign(this.$data, this.$options.data()); // seta para função estado inicial
    },
    setOperation(operation) {
      if (this.current === 0) {
        //
        this.operation = operation;
        this.current = 1; // setar segunda posição do array para ser alterado
        this.clearDisplay = true; // limpa o display para começar a mostar o segundo valor da operação
      } else {
        const equals = operation === "="; // quando digito for igual, seta variável para true
        const currentOperation = this.operation; // operação atual
        const value1 = this.values[0]; // 

        switch (currentOperation) {
          case "+":
            this.values[0] = this.values[0] + this.values[1];
            break;
          case "-":
            this.values[0] = this.values[0] - this.values[1];
            break;
          case "*":
            this.values[0] = this.values[0] * this.values[1];
            break;
          case "/":
            this.values[0] = this.values[0] / this.values[1];
            break;
          default:
            this.values[0] = value1;
            console.log("Caiu no default!!!");
        }

        this.values[1] = 0; // seta o valor da segunda posição do array para entra de novo valor
        this.displayValue = this.values[0]; // renderiza no display o resultado do switch acima
        this.operation = equals ? null : operation;
        this.current = equals ? 0 : 1;
        this.clearDisplay = !equals

      }
    },
    addDigit(n) {
      // validação para não haver dois pontos na mesma expressão formando um valor inválido
      if (n === "." && this.displayValue.includes(".")) {
        return; // saia da função
      }

      if (n === "." && this.displayValue === "0") {
        return this.displayValue = "0."
      }

      
      const clearDisplay = this.displayValue === "0" || this.clearDisplay; // dois casos para setar variável para true

      const currentValue = clearDisplay ? "" : this.displayValue; // condição para setar string vazia (true) ou  valor atual (false)
      const displayValue = currentValue + n; // concatenação

      // setando variável do estado do objeto
      this.displayValue = displayValue;
      this.clearDisplay = false;

      // add digitos ao array values para operação matemática
      if (n !== ".") {
        const i = this.current; // valor de índice 0 ou 1
        const newValue = parseFloat(displayValue);
        this.values[i] = newValue;
      }

    }
  }
};
</script>

<style>
.calculator {
  height: 320px;
  width: 235px;
  border-radius: 5px;
  overflow: hidden;

  display: grid;
  grid-template-columns: repeat(4, 25%);
  grid-template-rows: 1fr 48px 48px 48px 48px 48px;
}
</style>
